name: "Enforce Action Policy"
on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  enforce-package-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Check for action violations"
        id: action-policy
        with:
          policy: allow
          policy-url: "https://gist.githubusercontent.com/rob-derosa/ba7ecb82b164eca456142337acbdf6c0/raw/0c177df0dfa3e6dfe65007dd9ed49f1caafb8741/actions_policy.json"
          fail-if-violations: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          
          
